import { Share } from 'react-native';
import { FolderContextModel } from '../models/folderContext.model';
import { ScreenshotModel } from '../models/screenshot.model';
import { loggerService } from './loggerService';

export type ExportFormat = 'pdf' | 'markdown' | 'text';

export interface ExportResult {
  format: ExportFormat;
  content: string;
  title: string;
  mimeType: string;
  dataUri?: string;
}

export class FolderContextExportService {
  /**
   * Exports folder context to GitHub-flavored Markdown.
   */
  generateMarkdown(
    context: FolderContextModel,
    categoryName: string,
    screenshots: ScreenshotModel[] = []
  ): string {
    const lines: string[] = [];
    const dateStr = context.lastUpdatedAt
      ? new Date(context.lastUpdatedAt).toLocaleString()
      : new Date().toLocaleString();

    lines.push(`# ${categoryName} — Living Folder Context`);
    lines.push(`*Generated by ContextVault on ${dateStr}*`);
    lines.push('');

    // Metadata Badge list
    const confidencePct = Math.round((context.confidence || 1.0) * 100);
    lines.push(`> **Confidence:** ${confidencePct}% AI Match | **Screenshots Indexed:** ${screenshots.length || context.screenshotCount || 0}`);
    lines.push('');

    // 1. Executive Summary
    lines.push('## 📝 Executive Summary');
    lines.push(
      context.summary ||
        `Structured intelligence dossier compiled for ${categoryName} from device screenshots.`
    );
    lines.push('');

    // 2. Key Insights & Topics
    if (context.keywords && context.keywords.length > 0) {
      lines.push('## 💡 Key Insights & Topics');
      for (const topic of context.keywords) {
        lines.push(`- **${topic}**`);
      }
      lines.push('');
    }

    // 3. Extracted Entities
    const structured = context.structuredEntities;
    if (structured) {
      const hasEntities =
        (structured.organizations && structured.organizations.length > 0) ||
        (structured.payments && structured.payments.length > 0) ||
        (structured.shopping && structured.shopping.length > 0) ||
        (structured.documents && structured.documents.length > 0) ||
        (structured.people && structured.people.length > 0) ||
        (structured.urls && structured.urls.length > 0);

      if (hasEntities) {
        lines.push('## 📦 Extracted Entities');

        if (structured.organizations && structured.organizations.length > 0) {
          lines.push('### 🏢 Organizations & Merchants');
          for (const item of structured.organizations) {
            lines.push(`- ${item}`);
          }
          lines.push('');
        }

        if (structured.payments && structured.payments.length > 0) {
          lines.push('### 💳 Payments & Financial Values');
          for (const item of structured.payments) {
            lines.push(`- \`${item}\``);
          }
          lines.push('');
        }

        if (structured.shopping && structured.shopping.length > 0) {
          lines.push('### 🛍️ Shopping & Products');
          for (const item of structured.shopping) {
            lines.push(`- ${item}`);
          }
          lines.push('');
        }

        if (structured.documents && structured.documents.length > 0) {
          lines.push('### 📄 Documents & Reference IDs');
          for (const item of structured.documents) {
            lines.push(`- ${item}`);
          }
          lines.push('');
        }

        if (structured.people && structured.people.length > 0) {
          lines.push('### 👤 People & Contacts');
          for (const item of structured.people) {
            lines.push(`- ${item}`);
          }
          lines.push('');
        }

        if (structured.urls && structured.urls.length > 0) {
          lines.push('### 🔗 Links & URLs');
          for (const item of structured.urls) {
            lines.push(`- [${item}](${item})`);
          }
          lines.push('');
        }
      }
    }

    // 4. Action Items Checklist
    if (context.tasks && context.tasks.length > 0) {
      lines.push('## ✅ Action Items');
      for (const task of context.tasks) {
        const checkbox = task.isCompleted ? '[x]' : '[ ]';
        lines.push(`- ${checkbox} ${task.title}${task.dueDate ? ` *(Due: ${task.dueDate})*` : ''}`);
      }
      lines.push('');
    }

    // 5. Timeline
    if (context.timeline && context.timeline.length > 0) {
      lines.push('## ⏳ Chronological Timeline');
      for (const item of context.timeline) {
        const captured = item.capturedAt
          ? new Date(item.capturedAt).toLocaleDateString()
          : 'Recent';
        lines.push(`- **${captured} — ${item.title}**`);
        if (item.description) {
          lines.push(`  ${item.description}`);
        }
      }
      lines.push('');
    }

    // 6. Source Screenshots
    if (screenshots.length > 0) {
      lines.push(`## 📸 Source Screenshots (${screenshots.length})`);
      for (let i = 0; i < screenshots.length; i++) {
        const s = screenshots[i];
        const date = s.createdAt ? new Date(s.createdAt).toLocaleDateString() : 'N/A';
        const snippet = s.ocrText ? ` — *"${s.ocrText.slice(0, 80).replace(/\n/g, ' ')}..."*` : '';
        lines.push(`${i + 1}. **${s.fileName}** (${date})${snippet}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('*Exported securely from ContextVault. All analysis performed on-device.*');

    return lines.join('\n');
  }

  /**
   * Exports folder context to clean ASCII plain text.
   */
  generatePlainText(
    context: FolderContextModel,
    categoryName: string,
    screenshots: ScreenshotModel[] = []
  ): string {
    const divider = '='.repeat(76);
    const subDivider = '-'.repeat(76);
    const lines: string[] = [];
    const dateStr = context.lastUpdatedAt
      ? new Date(context.lastUpdatedAt).toLocaleString()
      : new Date().toLocaleString();

    lines.push(divider);
    lines.push(`CONTEXTVAULT FOLDER INTELLIGENCE REPORT`);
    lines.push(`Category:   ${categoryName.toUpperCase()}`);
    lines.push(`Generated:  ${dateStr}`);
    const confidencePct = Math.round((context.confidence || 1.0) * 100);
    lines.push(`Confidence: ${confidencePct}% Match | Screenshots: ${screenshots.length || context.screenshotCount || 0}`);
    lines.push(divider);
    lines.push('');

    // 1. Executive Summary
    lines.push('1. EXECUTIVE SUMMARY');
    lines.push(subDivider);
    lines.push(
      context.summary ||
        `Structured intelligence dossier compiled for ${categoryName} from device screenshots.`
    );
    lines.push('');

    // 2. Key Insights
    if (context.keywords && context.keywords.length > 0) {
      lines.push('2. KEY TOPICS & INSIGHTS');
      lines.push(subDivider);
      for (const topic of context.keywords) {
        lines.push(`  • ${topic}`);
      }
      lines.push('');
    }

    // 3. Extracted Entities
    const structured = context.structuredEntities;
    if (structured) {
      lines.push('3. EXTRACTED ENTITIES');
      lines.push(subDivider);

      if (structured.organizations && structured.organizations.length > 0) {
        lines.push('  [Organizations & Merchants]');
        for (const item of structured.organizations) lines.push(`    - ${item}`);
      }

      if (structured.payments && structured.payments.length > 0) {
        lines.push('  [Payments & Financial Values]');
        for (const item of structured.payments) lines.push(`    - ${item}`);
      }

      if (structured.shopping && structured.shopping.length > 0) {
        lines.push('  [Shopping & Products]');
        for (const item of structured.shopping) lines.push(`    - ${item}`);
      }

      if (structured.documents && structured.documents.length > 0) {
        lines.push('  [Documents & IDs]');
        for (const item of structured.documents) lines.push(`    - ${item}`);
      }

      if (structured.people && structured.people.length > 0) {
        lines.push('  [People & Contacts]');
        for (const item of structured.people) lines.push(`    - ${item}`);
      }

      if (structured.urls && structured.urls.length > 0) {
        lines.push('  [Links & URLs]');
        for (const item of structured.urls) lines.push(`    - ${item}`);
      }
      lines.push('');
    }

    // 4. Action Items
    if (context.tasks && context.tasks.length > 0) {
      lines.push('4. ACTION ITEMS');
      lines.push(subDivider);
      for (const task of context.tasks) {
        const mark = task.isCompleted ? '[X]' : '[ ]';
        lines.push(`  ${mark} ${task.title}${task.dueDate ? ` (Due: ${task.dueDate})` : ''}`);
      }
      lines.push('');
    }

    // 5. Timeline
    if (context.timeline && context.timeline.length > 0) {
      lines.push('5. CHRONOLOGICAL TIMELINE');
      lines.push(subDivider);
      for (const item of context.timeline) {
        const date = item.capturedAt
          ? new Date(item.capturedAt).toLocaleDateString()
          : 'Recent';
        lines.push(`  • ${date}: ${item.title}`);
        if (item.description) {
          lines.push(`    ${item.description}`);
        }
      }
      lines.push('');
    }

    // 6. Source Screenshots
    if (screenshots.length > 0) {
      lines.push(`6. SOURCE SCREENSHOTS (${screenshots.length})`);
      lines.push(subDivider);
      for (let i = 0; i < screenshots.length; i++) {
        const s = screenshots[i];
        lines.push(`  ${i + 1}. ${s.fileName} (${s.createdAt || 'N/A'})`);
        if (s.ocrText) {
          lines.push(`     Snippet: "${s.ocrText.slice(0, 90).replace(/\s+/g, ' ')}..."`);
        }
      }
      lines.push('');
    }

    lines.push(divider);
    lines.push('Exported on-device by ContextVault. Non-destructive intelligence.');
    lines.push(divider);

    return lines.join('\n');
  }

  /**
   * Generates a valid standard PDF 1.4 document stream in pure TypeScript.
   */
  generatePdf(
    context: FolderContextModel,
    categoryName: string,
    screenshots: ScreenshotModel[] = []
  ): { raw: string; base64: string; dataUri: string } {
    // Collect printable lines
    const plainText = this.generatePlainText(context, categoryName, screenshots);
    const rawLines = plainText.split('\n');

    // Page geometry (US Letter 612 x 792 pt)
    const pageWidth = 612;
    const pageHeight = 792;
    const marginX = 45;
    const marginTop = 50;
    const marginBottom = 50;
    const lineHeight = 13;
    const maxLinesPerPage = Math.floor((pageHeight - marginTop - marginBottom) / lineHeight);

    // Word wrap lines so text doesn't overflow page margins
    const maxCharsPerLine = 78;
    const wrappedLines: string[] = [];
    for (const line of rawLines) {
      if (line.length <= maxCharsPerLine) {
        wrappedLines.push(line);
      } else {
        let remaining = line;
        while (remaining.length > maxCharsPerLine) {
          // Break at space if possible
          let breakIdx = remaining.lastIndexOf(' ', maxCharsPerLine);
          if (breakIdx <= 0) breakIdx = maxCharsPerLine;
          wrappedLines.push(remaining.slice(0, breakIdx));
          remaining = remaining.slice(breakIdx).trimStart();
        }
        if (remaining.length > 0) wrappedLines.push(remaining);
      }
    }

    // Split wrapped lines into pages
    const pages: string[][] = [];
    for (let i = 0; i < wrappedLines.length; i += maxLinesPerPage) {
      pages.push(wrappedLines.slice(i, i + maxLinesPerPage));
    }
    if (pages.length === 0) pages.push(['No content available.']);

    // Helper to escape PDF text syntax
    const escapePdf = (str: string): string => {
      return str
        .replace(/\\/g, '\\\\')
        .replace(/\(/g, '\\(')
        .replace(/\)/g, '\\)')
        // Replace non-ASCII with closest representation
        .replace(/[^\x20-\x7E]/g, ' ');
    };

    // Construct PDF Objects
    // Object 1: Catalog
    // Object 2: Pages Root
    // Object 3: Font (Courier for monospaced table alignment)
    // Object 4: Font Bold (Courier-Bold)
    // Object 5..(4 + N): Page objects
    // Object (5 + N)..(4 + 2N): Content stream objects
    const totalPages = pages.length;
    const fontCourierId = 3;
    const fontBoldId = 4;
    const firstPageObjId = 5;
    const firstStreamObjId = 5 + totalPages;

    const objects: { id: number; content: string }[] = [];

    // Catalog
    objects.push({
      id: 1,
      content: `<< /Type /Catalog /Pages 2 0 R >>`,
    });

    // Pages Root
    const kids = Array.from({ length: totalPages }, (_, i) => `${firstPageObjId + i} 0 R`).join(' ');
    objects.push({
      id: 2,
      content: `<< /Type /Pages /Kids [${kids}] /Count ${totalPages} >>`,
    });

    // Font Courier
    objects.push({
      id: fontCourierId,
      content: `<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`,
    });

    // Font Courier-Bold
    objects.push({
      id: fontBoldId,
      content: `<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold >>`,
    });

    // Page objects & Stream objects
    for (let p = 0; p < totalPages; p++) {
      const pageObjId = firstPageObjId + p;
      const streamObjId = firstStreamObjId + p;
      const pageLines = pages[p];

      // Page Object
      objects.push({
        id: pageObjId,
        content: `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${streamObjId} 0 R /Resources << /Font << /F1 ${fontCourierId} 0 R /F2 ${fontBoldId} 0 R >> >> >>`,
      });

      // Stream Content
      const streamCommands: string[] = ['BT'];
      let currentY = pageHeight - marginTop;

      // Header on every page
      streamCommands.push(`/F2 10 Tf ${marginX} ${currentY} Td (${escapePdf(`ContextVault • ${categoryName} Intelligence`)} ) Tj`);
      streamCommands.push(`0 -14 Td /F1 9 Tf (${escapePdf(`Page ${p + 1} of ${totalPages}`)}) Tj`);
      currentY -= 26;
      streamCommands.push(`0 -12 Td`);

      // Print page lines
      for (const line of pageLines) {
        const isHeader = line.startsWith('===') || line.startsWith('1.') || line.startsWith('2.') || line.startsWith('3.') || line.startsWith('4.') || line.startsWith('5.') || line.startsWith('6.');
        const fontChoice = isHeader ? '/F2 9.5 Tf' : '/F1 9 Tf';
        streamCommands.push(`${fontChoice} (${escapePdf(line)}) Tj 0 -${lineHeight} Td`);
      }

      streamCommands.push('ET');
      const streamData = streamCommands.join('\n');

      objects.push({
        id: streamObjId,
        content: `<< /Length ${streamData.length} >>\nstream\n${streamData}\nendstream`,
      });
    }

    // Sort by ID
    objects.sort((a, b) => a.id - b.id);

    // Build Byte Offsets and XREF table
    let pdf = `%PDF-1.4\n%\xE2\xE3\xCF\xD3\n`;
    const offsets: number[] = [];

    for (const obj of objects) {
      offsets[obj.id] = pdf.length;
      pdf += `${obj.id} 0 obj\n${obj.content}\nendobj\n`;
    }

    const startXref = pdf.length;
    const totalObjs = objects.length + 1; // including 0
    pdf += `xref\n0 ${totalObjs}\n`;
    pdf += `0000000000 65535 f \n`;

    for (let i = 1; i < totalObjs; i++) {
      const off = offsets[i] || 0;
      const padded = String(off).padStart(10, '0');
      pdf += `${padded} 00000 n \n`;
    }

    pdf += `trailer\n<< /Size ${totalObjs} /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

    // Convert to Base64
    const base64 = this.toBase64(pdf);
    const dataUri = `data:application/pdf;base64,${base64}`;

    return { raw: pdf, base64, dataUri };
  }

  /**
   * Helper to encode string to Base64 in React Native without Buffer dependency.
   */
  private toBase64(input: string): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
    let output = '';
    let i = 0;

    while (i < input.length) {
      const chr1 = input.charCodeAt(i++) & 0xff;
      const chr2 = i < input.length ? input.charCodeAt(i++) & 0xff : NaN;
      const chr3 = i < input.length ? input.charCodeAt(i++) & 0xff : NaN;

      const enc1 = chr1 >> 2;
      const enc2 = ((chr1 & 3) << 4) | (isNaN(chr2) ? 0 : chr2 >> 4);
      let enc3 = isNaN(chr2) ? 64 : ((chr2 & 15) << 2) | (isNaN(chr3) ? 0 : chr3 >> 6);
      let enc4 = isNaN(chr3) ? 64 : chr3 & 63;

      output += chars.charAt(enc1) + chars.charAt(enc2) + chars.charAt(enc3) + chars.charAt(enc4);
    }

    return output;
  }

  /**
   * Exports folder context and triggers the native Android/iOS share sheet.
   */
  async shareExport(
    format: ExportFormat,
    context: FolderContextModel,
    categoryName: string,
    screenshots: ScreenshotModel[] = []
  ): Promise<ExportResult> {
    const sanitizedTitle = categoryName.replace(/[^a-zA-Z0-9_-]/g, '_');

    try {
      let content = '';
      let mimeType = 'text/plain';
      let fileName = `${sanitizedTitle}_Context.txt`;
      let dataUri: string | undefined;

      switch (format) {
        case 'markdown':
          content = this.generateMarkdown(context, categoryName, screenshots);
          mimeType = 'text/markdown';
          fileName = `${sanitizedTitle}_Context.md`;
          await Share.share({
            title: fileName,
            message: content,
          });
          break;

        case 'text':
          content = this.generatePlainText(context, categoryName, screenshots);
          mimeType = 'text/plain';
          fileName = `${sanitizedTitle}_Context.txt`;
          await Share.share({
            title: fileName,
            message: content,
          });
          break;

        case 'pdf': {
          const pdfResult = this.generatePdf(context, categoryName, screenshots);
          content = pdfResult.raw;
          dataUri = pdfResult.dataUri;
          mimeType = 'application/pdf';
          fileName = `${sanitizedTitle}_Context.pdf`;

          // Share PDF report with both clean text summary and PDF data URI
          const summaryText = this.generatePlainText(context, categoryName, screenshots);
          await Share.share({
            title: fileName,
            message: summaryText,
            url: dataUri,
          });
          break;
        }
      }

      loggerService.info('Storage', `Exported folder context for "${categoryName}" as ${format.toUpperCase()}`);

      return {
        format,
        content,
        title: fileName,
        mimeType,
        dataUri,
      };
    } catch (err: any) {
      loggerService.error('Storage', `Failed to export folder context as ${format}`, err);
      throw err;
    }
  }
}

export const folderContextExportService = new FolderContextExportService();
