export interface CategoryModel {
  id: string;
  name: string;
  parentId?: string | null;
  parentCategoryId?: string | null;
  iconName: string;
  icon?: string;
  colorHex: string;
  color?: string;
  description?: string;
  isSystem: boolean;
  orderIndex: number;
  screenshotCount?: number;
  isFavorite?: boolean;
  path?: string;
  createdOn?: string;
  updatedAt?: string;
  coverUri?: string | null;
  manualCoverUri?: string | null;
  averageConfidence?: number;
  storageSizeBytes?: number;
  favoriteCount?: number;
  ocrCount?: number;
  visionCount?: number;
  subCategories?: CategoryModel[];
}

export interface FolderStatistics {
  categoryId: string;
  categoryName: string;
  screenshotCount: number;
  favoriteCount: number;
  ocrCount: number;
  visionCount: number;
  averageConfidence: number;
  storageSizeBytes: number;
  lastAnalysisTime?: string | null;
  coverUri?: string | null;
  manualCoverUri?: string | null;
}

export const UNSORTED_CATEGORY_ID = 'unsorted';
export const UNSORTED_CATEGORY_NAME = 'Unsorted';

export const UNSORTED_CATEGORY: CategoryModel = {
  id: UNSORTED_CATEGORY_ID,
  name: UNSORTED_CATEGORY_NAME,
  parentId: null,
  parentCategoryId: null,
  iconName: 'help-circle-outline',
  colorHex: '94A3B8',
  description: 'Screenshots awaiting AI classification',
  isSystem: true,
  orderIndex: 999,
  screenshotCount: 0,
  isFavorite: false,
  path: '/Unsorted',
  createdOn: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  subCategories: [],
};

export const DEFAULT_CATEGORIES: CategoryModel[] = [
  {
    id: 'finance',
    name: 'Finance',
    parentId: null,
    parentCategoryId: null,
    iconName: 'wallet-outline',
    colorHex: '10B981',
    description: 'UPI, bank payments, receipts, invoices & transactions',
    isSystem: true,
    orderIndex: 1,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Finance',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    parentId: null,
    parentCategoryId: null,
    iconName: 'bag-handle-outline',
    colorHex: 'F97316',
    description: 'Amazon, Flipkart, Myntra, orders & wishlists',
    isSystem: true,
    orderIndex: 2,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Shopping',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'food_delivery',
    name: 'Food Delivery',
    parentId: null,
    parentCategoryId: null,
    iconName: 'fast-food-outline',
    colorHex: 'EF4444',
    description: 'Swiggy, Zomato, Blinkit, Zepto orders & receipts',
    isSystem: true,
    orderIndex: 3,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Food Delivery',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'chats',
    name: 'Chats',
    parentId: null,
    parentCategoryId: null,
    iconName: 'chatbubble-ellipses-outline',
    colorHex: '22C55E',
    description: 'WhatsApp, Telegram, Messenger & SMS conversations',
    isSystem: true,
    orderIndex: 4,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Chats',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'social_media',
    name: 'Social Media',
    parentId: null,
    parentCategoryId: null,
    iconName: 'share-social-outline',
    colorHex: 'EC4899',
    description: 'Instagram, Facebook, X, Reddit posts & reels',
    isSystem: true,
    orderIndex: 5,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Social Media',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'travel',
    name: 'Travel',
    parentId: null,
    parentCategoryId: null,
    iconName: 'airplane-outline',
    colorHex: '06B6D4',
    description: 'IRCTC, flight tickets, boarding passes & hotel bookings',
    isSystem: true,
    orderIndex: 6,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Travel',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'health',
    name: 'Health',
    parentId: null,
    parentCategoryId: null,
    iconName: 'medkit-outline',
    colorHex: '14B8A6',
    description: 'Medical prescriptions, lab reports & medicines',
    isSystem: true,
    orderIndex: 7,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Health',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'education',
    name: 'Education',
    parentId: null,
    parentCategoryId: null,
    iconName: 'school-outline',
    colorHex: '3B82F6',
    description: 'Study notes, PDFs, courses & tutorials',
    isSystem: true,
    orderIndex: 8,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Education',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'work',
    name: 'Work',
    parentId: null,
    parentCategoryId: null,
    iconName: 'briefcase-outline',
    colorHex: '6366F1',
    description: 'Slack, Teams, Gmail, Jira, sprints & corporate tasks',
    isSystem: true,
    orderIndex: 9,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Work',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'documents',
    name: 'Documents',
    parentId: null,
    parentCategoryId: null,
    iconName: 'document-text-outline',
    colorHex: 'F59E0B',
    description: 'Aadhaar, PAN, Passport, contracts & official IDs',
    isSystem: true,
    orderIndex: 10,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Documents',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    parentId: null,
    parentCategoryId: null,
    iconName: 'play-circle-outline',
    colorHex: 'A855F7',
    description: 'YouTube, Netflix, Spotify, games & memes',
    isSystem: true,
    orderIndex: 11,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Entertainment',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'utilities',
    name: 'Utilities',
    parentId: null,
    parentCategoryId: null,
    iconName: 'flash-outline',
    colorHex: 'EAB308',
    description: 'OTP SMS, mobile recharge, electricity & water bills',
    isSystem: true,
    orderIndex: 12,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Utilities',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'other',
    name: 'Other',
    parentId: null,
    parentCategoryId: null,
    iconName: 'help-circle-outline',
    colorHex: '94A3B8',
    description: 'General screenshots awaiting classification',
    isSystem: true,
    orderIndex: 13,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Other',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  // Legacy aliases to prevent breakages in existing references
  {
    id: 'projects',
    name: 'Projects',
    parentId: null,
    parentCategoryId: null,
    iconName: 'briefcase-outline',
    colorHex: '6366F1',
    description: 'Work projects, sprints, tasks & deliverables',
    isSystem: true,
    orderIndex: 14,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Projects',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'tech',
    name: 'Tech',
    parentId: null,
    parentCategoryId: null,
    iconName: 'code-slash-outline',
    colorHex: '8B5CF6',
    description: 'Code snippets, error logs, GitHub & terminal',
    isSystem: true,
    orderIndex: 15,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Tech',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'learning',
    name: 'Learning',
    parentId: null,
    parentCategoryId: null,
    iconName: 'school-outline',
    colorHex: '3B82F6',
    description: 'Tutorials, articles & courses',
    isSystem: true,
    orderIndex: 16,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Learning',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  {
    id: 'social',
    name: 'Social',
    parentId: null,
    parentCategoryId: null,
    iconName: 'chatbubble-ellipses-outline',
    colorHex: 'EC4899',
    description: 'Social apps & messages',
    isSystem: true,
    orderIndex: 17,
    screenshotCount: 0,
    isFavorite: false,
    path: '/Social',
    createdOn: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    subCategories: [],
  },
  UNSORTED_CATEGORY,
];
